# Generated by Django 4.2.6 on 2023-11-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
