# Generated by Django 4.2.6 on 2023-11-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0007_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
