# Generated by Django 4.2.6 on 2023-11-28 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecomapp', '0010_alter_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartData',
        ),
    ]
