# Generated by Django 4.2.6 on 2023-11-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0011_rename_cart_cartdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdata',
            old_name='ProductsId',
            new_name='productId',
        ),
    ]
