# Generated by Django 4.2.7 on 2023-12-20 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecomapp', '0015_billing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_address',
            new_name='deliveryAddress',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMode', models.CharField(max_length=20)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('orederDate', models.DateField(auto_now_add=True, null=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomapp.deliveryaddress')),
                ('items', models.ManyToManyField(to='Ecomapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
